# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- main

pool:
  vmImage: 'macos-latest'

variables:
  - group: iOS-pipeline

steps:
- task: InstallAppleCertificate@2
  inputs:
   certSecureFile: '$(p12FileName)'
   certPwd: '$(p12Password)'
   keychain: 'temp'
   deleteCert: true  
- task: InstallAppleProvisioningProfile@1
  inputs:
   provisioningProfileLocation: 'secureFiles'
   provProfileSecureFile: '$(provisioningProfile)'
   removeProfile: true
- task: Xcode@5
  inputs:
    actions: 'build'
    scheme: ''
    sdk: 'iphoneos'
    configuration: 'Release'
    xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'
    xcodeVersion: 'default' # Options: 8, 9, 10, 11, 12, default, specifyPath
    packageApp: true
    signingOption: 'manual'
    signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
    provisioningProfileUuid: '$(APPLE_PROV_PROFILE_UUID)'
    
- task: CopyFiles@2
  inputs:
    contents: '**/*.ipa'
    targetFolder: '$(build.artifactStagingDirectory)'
    overWrite: true
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(build.artifactStagingDirectory)/output/$(sdk)/$(configuration)' 
    artifactName: 'drop' 
    publishLocation: 'Container'
    
- task: AppCenterDistribute@3
  inputs:
      serverEndpoint: 'App Center connection'
      appSlug: 'cscyhenry1-gmail.com/HelloChanel'
      appFile: '$(build.artifactstagingdirectory)/**/*.ipa'
      releaseNotesOption: 'file'
      releaseNotesFile: 'CHANGELOG'
      destinationType: 'groups'
      distributionGroupId: 'd5b96773-e18c-43b7-8385-0e3bb805f0d8'

- task: AppStoreRelease@1
  inputs:
    serviceEndpoint: 'first app store connection'
    releaseTrack: 'TestFlight'
    appIdentifier: 'comhenrytungtestapp10testapp'
    ipaPath: '$(build.artifactstagingdirectory)/**/*.ipa'
    appType: 'iOS'
    shouldSkipWaitingForProcessing: true
    shouldSkipSubmission: true
    appSpecificId: '6444382653'